import { type NextPage } from "next";
import Head from "next/head";

import Layout from "~/components/Layout";
import Playlists from "~/pages/playlists";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <Playlists />
        </div>
      </Layout>
    </>
  );
};

export default Home;
